services:
  - type: web
    name: gandhii-bai-crm
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm install path-to-regexp@6.2.1 --save-exact && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: true
      - key: VITE_API_URL
        value: https://crm.gandhibaideaddictioncenter.com/api
      - key: VITE_BASE_URL
        value: https://crm.gandhibaideaddictioncenter.com
    healthCheckPath: /api/test
